AMQP_URI: 'pyamqp://guest:guest@localhost'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
YOWSUP_USERNAME: '6281296216520'
YOWSUP_PASSWORD: 'VryU60eNZyPdENTiIpBCIH7PEH4='
TOKEN_RESEND_MESSAGES: 'test'
ENDPOINT_RESEND_MESSAGES: 'http://localhost:9000/send'
rpc_exchange: 'nameko-rpc'
max_workers: 1
parent_calls_tracked: 10
